kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "pods/log", "pods/portforward", "namespaces", "serviceaccounts", "endpoints", "persistentvolumeclaims"]
    verbs: ["create", "get", "update", "list", "delete", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "update", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["create", "get", "update", "list", "delete", "patch"]
  - apiGroups: ["traefik.containo.us"]
    resources: ["ingressroutes"]
    verbs: ["create", "get", "update", "list", "delete", "patch"]
  - apiGroups:
    - ''
    resources:
    - persistentvolumes
    verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ''
    resources:
    - persistentvolumes/status
    verbs:
    - update
  - apiGroups:
    - ''
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - ''
    resources:
    - persistentvolumeclaims/status
    verbs:
    - update
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - endpoints
    - services
    verbs:
    - create
    - delete
    - get
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
    - ''
    resources:
    - nodes
    verbs:
    - get
    - list
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - watch
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - create
    - patch
    - update
  - apiGroups:
    - ''
    resources:
    - endpoints
    verbs:
    - update
  - apiGroups:
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - events.k8s.io
    resources:
    - events
    verbs:
    - patch
  - apiGroups:
    - events.k8s.io
    resources:
    - events
    verbs:
    - update
