kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user
subjects:
  - kind: Group
    name: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user
  apiGroup: rbac.authorization.k8s.io
