kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/portforward", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "list", "watch"]
