# This workflow is triggered on tag push finishing with '-preprod'

name: CD preproduction

on:
  push:
    tags:
      - v*

jobs:
  build-push-preprod:
    name: Build push image ${{ matrix.app }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        app: [ "backend", "frontend" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucas.claisse@epitech.eu
          password: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.app }}
          tag-custom: "latest"
          tag-latest: false

      - name: Build and push ${{ matrix.app }} Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: .
          file: ./${{ matrix.app }}/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
